apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: drureplicas
  name: drureplicas
spec:
  replicas: 10
  selector:
    matchLabels:
      app: dru-replicas
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dru-replicas
    spec:
      containers:
      - image: httpd:2.4-trixie
        name: httpd
        resources: {}
status: {}
